# Generated by Django 5.1.1 on 2024-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chocolateproduct_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolateproduct',
            name='price',
            field=models.FloatField(),
        ),
    ]
