# Generated by Django 5.1.1 on 2024-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_product_chocolateproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolateproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
